INSERT INTO EXERCISES(ID, NAME, OWNER) VALUES (99, 'Pullover', 'Carlos');
INSERT INTO EXERCISES(ID, NAME, OWNER) VALUES (100, 'Bench Press', 'Carlos');
INSERT INTO EXERCISES(ID, NAME, OWNER) VALUES (101, 'Abs', 'Andrés');